### ISSUE TITLE
Failing test in opm-core

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-material#104]
Currently the `test_relpermdiagnistics` test in `opm-core` is failing. 

The failure is due to a failing assert here: https://github.com/OPM/opm-material/blob/master/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp#L374 

The test data used is here: https://github.com/OPM/opm-core/blob/master/tests/relpermDiagnostics.DATA#L61

So it is indeed 'correct' to fail the assertion, but it is not clear to me how this should be fixed:

1. Remove the `assert( )`?
2. Fix the test data?

**Comment by andlaus** [comment]
I think we had this before and we agreed to remove the assert. nobody opened a PR though, so this fell through the cracks...

**Comment by joakim-hove** [comment]
> and we agreed to remove the assert

OK - I'll add that to: https://github.com/OPM/opm-material/pull/103
