### ISSUE TITLE
pengrobinson test segfaults on Ubuntu 14.04 in Release

### ISSUE THREAD

**Issue by babrodtk** [OPM/opm-material#23]
On Ubuntu 14.04, stock, with gcc 4.82, the pengrobinson test fails:
```
vagrant@vagrant:~/workspace/opm/opm-material-build$ make test
Running tests...
Test project /home/vagrant/workspace/opm/opm-material-build
    Start 1: fluidmatrixinteractions
1/7 Test #1: fluidmatrixinteractions ..........   Passed    0.00 sec
    Start 2: pengrobinson
2/7 Test #2: pengrobinson .....................***Exception: SegFault  0.00 sec
    Start 3: ncpflash
3/7 Test #3: ncpflash .........................   Passed    0.03 sec
    Start 4: tabulation
4/7 Test #4: tabulation .......................   Passed   12.13 sec
    Start 5: 2dtables
5/7 Test #5: 2dtables .........................   Passed    0.02 sec
    Start 6: fluidsystems
6/7 Test #6: fluidsystems .....................   Passed   15.23 sec
    Start 7: immiscibleflash
7/7 Test #7: immiscibleflash ..................   Passed    0.03 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) =  32.48 sec

The following tests FAILED:
	  2 - pengrobinson (SEGFAULT)
Errors while running CTest
make: *** [test] Error 8
```
The relevant part of Testing/Temporary/LastTest.log is
```
2/7 Testing: pengrobinson
2/7 Test: pengrobinson
Command: "/home/vagrant/workspace/opm/opm-material-build/bin/test_pengrobinson"
Directory: /home/vagrant/workspace/opm/opm-material-build/tests
"pengrobinson" start time: Apr 09 08:15 UTC
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Failed.
"pengrobinson" end time: Apr 09 08:15 UTC
"pengrobinson" time elapsed: 00:00:00
----------------------------------------------------------
```

In debug mode, however, it appears to succeed:
```
vagrant@vagrant:~/workspace/opm/opm-material-build$ make test
Running tests...
Test project /home/vagrant/workspace/opm/opm-material-build
    Start 1: fluidmatrixinteractions
1/7 Test #1: fluidmatrixinteractions ..........   Passed    0.00 sec
    Start 2: pengrobinson
2/7 Test #2: pengrobinson .....................   Passed   43.68 sec
    Start 3: ncpflash
3/7 Test #3: ncpflash .........................   Passed    0.04 sec
    Start 4: tabulation
4/7 Test #4: tabulation .......................   Passed   14.63 sec
    Start 5: 2dtables
5/7 Test #5: 2dtables .........................   Passed    0.10 sec
    Start 6: fluidsystems
6/7 Test #6: fluidsystems .....................   Passed   18.25 sec
    Start 7: immiscibleflash
7/7 Test #7: immiscibleflash ..................   Passed    0.03 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) =  81.76 sec
```
and the same part of the log file:
```
2/7 Testing: pengrobinson
2/7 Test: pengrobinson
Command: "/home/vagrant/workspace/opm/opm-material-build/bin/test_pengrobinson"
Directory: /home/vagrant/workspace/opm/opm-material-build/tests
"pengrobinson" start time: Apr 09 08:19 UTC
Output:
----------------------------------------------------------
alpha[-] p[Pa] S_g[-] rho_o[kg/m^3] rho_g[kg/m^3] <M_o>[kg/mol] <M_g>[kg/mol] R_s[m^3/m^3] B_g[-] B_o[-]
0.98 4.59137e+07 7.71576e-28 593.853 153.824 0.0888336 0.012423 100.722 0.00516612 1.0375 
```
tons of lines removed for brevity, before it ends with
```
{ 116260, 0.0846657 },
{ 108267, 0.0390865 }
};
<end of output>
Test time =  43.68 sec
----------------------------------------------------------
Test Passed.
"pengrobinson" end time: Apr 09 08:20 UTC
"pengrobinson" time elapsed: 00:00:43
----------------------------------------------------------
```

**Comment by bska** [comment]
Confirmed on Linux Mint 17.1 with GCC 4.8.2
```
86% tests passed, 1 tests failed out of 7	opt/seq/dune-2.2.1/opm-material
86% tests passed, 1 tests failed out of 7	opt/seq/dune-2.3.1/opm-material
86% tests passed, 1 tests failed out of 7	opt/mpi/dune-2.2.1/opm-material
86% tests passed, 1 tests failed out of 7	opt/mpi/dune-2.3.1/opm-material
```
The "1 test failed" is `test_pengrobinson`.

**Comment by andlaus** [comment]
I've seen this issue on and off, and I have to confess that I am quite puzzled by it: I suspect that it is a compiler-issue because the test fails for some compilers, but succeeds for later ones and then suddenly re-appears for new compiler releases. Also, valgrind, ASAN and UBSAN did not complain last time I checked, but I will re-run them again later today...

can you provide a backtrace for the failing case? It would be most useful if you used `-Og` instead of `-O[23]`.

**Comment by andlaus** [comment]
ok, I digged into this and found another "fun" fact which points to the compiler: add any output statement to the `luDecomposition()` method of the `Dune::DenseMatrix` class and it suddenly works even with optimizations enabled. In addition, using clang 3.5.0 it works fine in optimized mode, so this seems to be a GCC issue. Now I'd "only" need to find out which optimization pass causes it...

**Comment by andlaus** [comment]
I digged further and found out that this error only occurs with GCC 4.8 with '-O3' and that it is does not occur if either `-O2` or GCC 4.9 is used. interestingly enough when using GCC 4.8 and '-O2' plus manually enabling the additional optimization flags for `-O3` documented at  https://gcc.gnu.org/onlinedocs/gcc-4.8.3/gcc/Optimize-Options.html also did not trigger this error. (On that front it may be that GCC 4.8.4 also fixes this issue, I've only tested it on 4.8.3.)

I'm getting quite confident that this issue is not something which can be fixed here, so I close it now. if I made a mistake, please re-open...

**Comment by atgeirr** [comment]
I agree that it cannot be fixed here, now, by us, but we should consider working around it, for example by recommending that Ubuntu 14.04 users use gcc 4.9.

**Comment by bska** [comment]
> for example by recommending that Ubuntu 14.04 users use gcc 4.9.

Or not use `-O3`.

**Comment by andlaus** [comment]
> Or not use `-O3`.

yep. that's what I'd also recommend. If I remember correctly, the GCC devs explicitly say that `-O3` may be unsafe. Also, I've seen cases were the performance with `-O3` was *worse* than with `-O2`... (even in cases where it is faster, I never experienced a speed up of more than 5 percent.)
