### ISSUE TITLE
Where is lapack required?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-material#277]
On one machine CMake showed an error that no lapack is available on the system. Can someone tell me where the usage of lapack is mandatory? I tried to find it myself but could not.

**Comment by akva2** [comment]
i actually don't think lapack is required, it's just "bundled" with blas.

**Comment by akva2** [comment]
edit: scratch that. the dependency comes through libecl.

**Comment by andlaus** [comment]
hm, I think it would simplify things considerably if the file I/O things of libecl were moved into opm-parser and/or opm-output. as far as I can see, this would also solve the issues with the LAPACK/BLAS dependencies. any thoughts @joakim-hove?

**Comment by joakim-hove** [comment]
> hm, I think it would simplify things considerably if the file I/O things of libecl were moved into opm-parser and/or opm-output. as far as I can see, this would also solve the issues with the LAPACK/BLAS dependencies. any thoughts @joakim-hove?

Well - at least we are working quite hard to trim down the surface of libecl, and removing the blas/lapack dependency is on the way. It is actually optional as is already, but if you have built a library with `BLAS/LAPACK` available - and then later do not have access to it - then things certainly blow up.

**Comment by andlaus** [comment]
this issue seems to be stale and has likely been resolved in the meantime. closing, feel free to reopen if it still applies.
