### ISSUE TITLE
Premature version upgrade breaks build of OPM

### ISSUE THREAD

**Issue by blattms** [OPM/opm-material#295]
Since f97f34ad5e96f88b1e3f019ec64a57e57dc75daa (what happend to using pull requests, anyway) I cannot build the master of OPM anymore:

```
--- calling bexec for opm-material ---
loading initial cache file ../../opts.cmake
CMake Error at /home/mblatt/src/dune/opm-2.6/opm-common/cmake/Modules/OpmFind.cmake:180 (find_package):
  Could not find a configuration file for package "opm-common" that is
  compatible with requested version "2018.10".

  The following configuration files were considered but not accepted:

    /home/mblatt/src/dune/opm-2.6/opm-common/opm-parallel/opm-common-config.cmake, version: 2018.04

Call Stack (most recent call first):
  /home/mblatt/src/dune/opm-2.6/opm-common/cmake/Modules/OpmPackage.cmake:191 (find_and_append_package_to)
  opm-material-prereqs.cmake:25 (find_package_deps)
  CMakeLists.txt:66 (include)


-- Configuring incomplete, errors occurred!
See also "/home/mblatt/src/dune/opm-2.6/opm-material/opm-parallel/CMakeFiles/CMakeOutput.log".
See also "/home/mblatt/src/dune/opm-2.6/opm-material/opm-parallel/CMakeFiles/CMakeError.log".
--- Failed to build opm-material ---
Terminating dunecontrol due to previous errors!
```

**Comment by blattms** [comment]
Same problem in ewoms BTW

**Comment by blattms** [comment]
There to without PR. Accidental push to wrong repo/in wrong branch?

**Comment by andlaus** [comment]
yeah, I mistyped the remote, I wanted to push it into my own fork. since this is pretty trivial, I'll adapt the version of the other modules. Note that this is actually a problem of the default OPM build system: dune.module does not request any specific version of the opm modules. @akva2: I guess this should be fixed?

**Comment by andlaus** [comment]
ok, PRs for the other modules opened, closing this issue for now. if I forgot something, please add a comment.

**Comment by akva2** [comment]
i don't get what should be fixed. we make sure that we do not mix versions of opm modules. it's done on purpose.

**Comment by blattms** [comment]
The tight version checks seem like a feature to me, too.

**Comment by andlaus** [comment]
I think that the behavior of the Dune build system semantically correct here: if no version is specified for the dependencies, any version should be accepted, and currently opm modules do not specify any version. (whether a minimum version should be specified is a different discussion.)

Anyway, not a big deal.
