### ISSUE TITLE
a question about "opm-material-prereqs.cmake"

### ISSUE THREAD

**Issue by G86char** [OPM/opm-material#359]
There is a piece of code "find_package_deps(opm-material)" in the "opm-material-prereqs.cmake" file.  

I am confused about this "find_package_deps(opm-material)" code.  It is like the "find_package()" of CMake, but it seems that this code is not a CMake command.   Could someone explain this code please?   Thanks!

**Comment by akva2** [comment]
It is a wrapper around find_package with some additions. The macros are found in opm-common/cmake/Modules

**Comment by G86char** [comment]
@avkv2   Thanks so much for your reply and answer. 

Following your instruction, I have found this macros in "OpmPackage.cmake".
