### ISSUE TITLE
Bug in Spline.hpp

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-material#527]
Line 
https://github.com/OPM/opm-material/blob/4181950059ea9afa846002c1538bc468f8be2c89/opm/material/common/Spline.hpp#L1247
triggers an unused variable warning, for good reason. The variable is equal to `i` or (if `reverse` is true) counting down backwards. However, for actual indexing, `i` is always used, not `idx`.

There also seems to be no unit tests for this code, which makes me a bit reluctant about fixing it.

**Comment by totto82** [comment]
> There also seems to be no unit tests for this code, which makes me a bit reluctant about fixing it.

I think keeping the option of using splines (for instance in the table evaluations)  could be valuable at some point. But before usage it needs a proper unit test, I agree. But in the meantime a suggest a quick fix here to avoid the warning(s). I can provide the fix.

**Comment by akva2** [comment]
i believe 1210+ is plagued by the same. it is rather copy-paste.
