### ISSUE TITLE
ECLMaterialLawManager::materialParams_ behaves/is used inconsistently

### ISSUE THREAD

**Issue by blattms** [OPM/opm-material#65]
https://github.com/OPM/opm-material/blob/12376bc3d262ffca0401a8477f3c13ba938311af/opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp#L210-L228: In the functions `ECLMaterialLawManager::materialLawParam(unsigned elemetIdx)` there is a switch on `ECLMaterialLawManager::hasElementSpecificParameters()`. If `true` the size is assumed to equal to the number elements in the grid, other it is supposed to be the number of `satNumRegions`.

Nevertheless, during `ECLMaterialLawManager::init` the same switch is used to either call `ECLMaterialLawManager::initElemSpecific_` or `ECLMaterialLawManager::initNonElemSpecific_`. But both methods create `ECLMaterialLawManager::materialLawParams_` with the same size as the number of elements and initialize one entry for each element. See https://github.com/OPM/opm-material/blob/12376bc3d262ffca0401a8477f3c13ba938311af/opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp#L548-L561 and https://github.com/OPM/opm-material/blob/12376bc3d262ffca0401a8477f3c13ba938311af/opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp#L382-L386.

If I am not missing something then this could lead to rather unwanted behaviour during a simulation and should be resolved. I would propose to always create one entry in `ECLMaterialLawManager::materialLawParams_` for each cell and remove the switches from `ECLMaterialLawManager::materialLawParams()` as this seems easier to grasp as varying sizes depending on the properties.

**Comment by blattms** [comment]
@andlaus I have not checked it yet, but this bug could explain the deviations I saw during swatInit in the parallel Norne runs. During it the function `materialLawParams(unsigned elemIdx)` to select the parameters used to calculate the capillary pressure. Due to the distributed grid and the inconsistent initialization the values stored in materialLawParams_[satNumRegions_[elemIdx]]` are different in the two cases as the associated global indexes are different.

**Comment by andlaus** [comment]
> If I am not missing something then this could lead to rather unwanted behaviour during a simulation and should be resolved.

You're probably right that the array size is wrong. Though I'm pretty sure that the most severe consequence is some wasted memory if the parameters for the material law are not element specific, i.e., if end point scaling and hysteresis is disabled. (If it was totally wrong, it would crash for the SPE1 and SPE9 decks.) I'll look into this on monday.

**Comment by andlaus** [comment]
> @andlaus I have not checked it yet, but this bug could explain the deviations I saw during swatInit in the parallel Norne runs. During it the function materialLawParams(unsigned elemIdx) to select the parameters used to calculate the capillary pressure. Due to the distributed grid and the inconsistent initialization the values stored in materialLawParams_[satNumRegions_[elemIdx]]` are different in the two cases as the associated global indexes are different.

that would only be the case if SWATINIT is enabled, but neither endpoint scaling nor hysteresis is (not sure if this is allowed, @osae or @joakim-hove probably know this). if it is, I agree that the material parameters should always be element-specific.

**Comment by alfbr** [comment]
Maybe I misunderstand you, but afaik SWATINIT, endpoint scaling and hysterisis are all three in use in the Norne model.

**Comment by blattms** [comment]
> > If I am not missing something then this could lead to rather unwanted behaviour during a simulation and should be resolved.
> 
> You're probably right that the array size is wrong. Though I'm
> pretty sure that the most severe consequence is some wasted memory
> if the parameters for the material law are not element specific,
> i.e., if end point scaling and hysteresis is disabled. (If it was
> totally wrong, it would crash for the SPE1 and SPE9 decks.) I'll
> look into this on monday.

The wasted memory is not a problem that I am concerned about (I am
about overexcessive use of pointers, but that is another topic).

The problem is that whenever neither end point scaling
nor hysteresis is used, the parameters retrieved when calculating the
capillary pressure for a cell are not guaranteed to be the parameters
stored for this cell. For cell `elemIdx` the code stores the parameters at
index `elemIdx`, see
https://github.com/OPM/opm-material/blob/12376bc3d262ffca0401a8477f3c13ba938311af/opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp#L385. But
when calculating the pressure the parameters are retrieved using
`materialLawParams(unsigned elemIdx)` which means that
`materialLawParams_[satNumRegionIdx_[elemIdx]]` is used for that cell.

@abir as norne does use one of those it should not be problem there.

@andlaus While at it wouldn't it make sense to get rid off the switch
in `oilWaterScaledEpsInfoDrainage()`, always store one for each
cell in oilWaterScaledEpsInfoDrainage_ (and waste memory)?

**Comment by blattms** [comment]
BTW the problem even affects `SaturationPropsFromDeck::capPress`
because it uses the `EclMaterialLawManager::materialLawParams` to get
the parameters for calculating.

**Comment by andlaus** [comment]
I agree that it is a bug. The only thing which I'm kind of undecided as of yet is whether it is better to kill the `initNonElementSpecific_()` method altogether or to fix it. I'm currently inclined to kill it to make that code simpler, but if the non-EPS, non-hysteresis case is common for huge decks, fixing it may be the better option because of the memory savings. Question to people which are wiser than me (e.g., @abir): Is it common?

**Comment by andlaus** [comment]
>  @andlaus While at it wouldn't it make sense to get rid off the switch in `oilWaterScaledEpsInfoDrainage()`, always store one for each cell in oilWaterScaledEpsInfoDrainage_ (and waste memory)?

I'll have a look, but IIRC the scaled parameters are already unconditionally element specific. the unscaled ones are one-per-satregion and I suspect that the result would be slightly slower because of additional cache misses if these points were copied into the material parameter objects themselves. I haven't measured this though, but I suppose it at least won't be faster and I'm reasonably certain that the init code won't become any simpler if it was changed...

**Comment by alfbr** [comment]
EPS is common, hysterisis is less common. Still, we should cater to both cases, so I do believe we want full flexibility in this setting.

**Comment by andlaus** [comment]
the question is not whether both cases should be supported (they are and will be unconditionally), but whether large decks (i.e., >= 50M cells) often use EPS and hysteresis or not. if they normally use it, there's not much point for optimizing memory consumption in the non-usage case. (also, such large decks could be uncommon, too.)

**Comment by blattms** [comment]
I am all for simpler code and less if-else switches that change the
size of data structures.

**Comment by alfbr** [comment]
It is easier for me to have an opinion if I get some qualifiers. Simplicity is always nice and memory consumption is generally less of an issue than performance. Sounds like we should go for the kill :-)

**Comment by andlaus** [comment]
I hope that #68 killed this beast. if not, please re-open.
