### ISSUE TITLE
Errors in Statoil when adding tests:

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-material#70]
I have not had the time to look at this at all - but here is the backtrace:
```
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1") 
CMake Error at /private/jenkins/jenkins/OPM/install/RH6/share/opm/cmake/Modules/OpmSatellites.cmake:285 (add_executable):
  add_executable called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:97 (opm_add_test)

CMake Error at /private/jenkins/jenkins/OPM/install/RH6/share/opm/cmake/Modules/OpmSatellites.cmake:286 (target_link_libraries):
  Cannot specify link libraries for target "test_eclmateriallawmanager" which
  is not built by this project.
Call Stack (most recent call first):
  CMakeLists.txt:97 (opm_add_test)
```

**Comment by andlaus** [comment]
looks like the build directory is not properly reconfigured? (try removing and re-creating it.)

**Comment by joakim-hove** [comment]
OK - I have looked a bit more into this. 

1. The build fails with exactly the same error message also after: #71 
2. When building locally in full sibling mode it fails with the same error message.

Sorry - I don't understand ;-(

**Comment by andlaus** [comment]
hm, this issuse is currently hard to reproduce for me: could you check if the files `tests/test_eclmateriallawmanager.cpp` and `tests/test_eclblackoilpvt.cpp` are present in the source directory of opm-material?

**Comment by andlaus** [comment]
it could also be that opm-parser was build _after_ opm-material, but for opm-material being able to use it, opm-parser must be build _before_. since opm-parser is only an optional dependency, is it possible that this is yet another bug in the code for sibling builds?

**Comment by joakim-hove** [comment]
> could you check if the files `tests/test_eclmateriallawmanager.cpp` and `tests/test_eclblackoilpvt.cpp` are present ...

Yes - they are present; come on - I have updated!

**Comment by joakim-hove** [comment]
>it could also be that opm-parser was build after opm-material, but for opm-material being able to use it, opm-parser must be build before

opm-parser is built in a sibling location before configuring opm-material, and the Findopm-parser succeeds:
```
-- Performing Test HAVE_OPM_PARSER
-- Performing Test HAVE_OPM_PARSER - Success
-- Found opm-parser: /private/joaho/work/OPM/opm-parser ....
```

**Comment by andlaus** [comment]
> Yes - they are present; come on - I have updated!

I was more worried that I forgot to add them to git. sometimes I get confused by a thicket of branches ;)

> opm-parser is built in a sibling location before configuring opm-material, and the Findopm-parser succeeds:

hm. what happens if you remove the `CONDITION OPM_PARSER_FOUND` arguments for the `opm_add_test()` calls in `CMakeLists.txt`?

**Comment by joakim-hove** [comment]
> hm. what happens if you remove the CONDITION OPM_PARSER_FOUND arguments for the opm_add_test() calls in CMakeLists.txt?

No change:
```
-- Writing config file "/private/joaho/work/OPM/opm-material/build/config.h"...
-- This build defaults to installing in /usr/local
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1") 
CMake Error at /private/joaho/work/OPM/opm-common/cmake/Modules/OpmSatellites.cmake:285 (add_executable):
  add_executable called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:97 (opm_add_test)


CMake Error at /private/joaho/work/OPM/opm-common/cmake/Modules/OpmSatellites.cmake:286 (target_link_libraries):
  Cannot specify link libraries for target "test_eclblackoilpvt" which is not
  built by this project.
Call Stack (most recent call first):
  CMakeLists.txt:97 (opm_add_test)
```

**Comment by joakim-hove** [comment]
Buth this:

```txt
opm_add_test(test_eclmateriallawmanager 
                        SOURCES tests/test_eclmateriallawmanager.cpp 
                        LIBRARIES ${OPM_PARSER_LIBRARIES} ${Boost_LIBRARIES} 
                        CONDITION OPM_PARSER_FOUND)

opm_add_test(test_fluidmatrixinteractions 
                    SOURCES tests/test_fluidmatrixinteractions.cpp 
                    LIBRARIES ${OPM_PARSER_LIBRARIES} ${Boost_LIBRARIES})
```

seems to work as expected.

**Comment by bska** [comment]
For what it's worth, I can make the test setup in [`CMakeLists.txt`](https://github.com/OPM/opm-material/blob/master/CMakeLists.txt#L97-L108) work unchanged if I apply the change below to [`opm-common/cmake/Modules/OpmSatellites.cmake`](https://github.com/OPM/opm-common/blob/master/cmake/Modules/OpmSatellites.cmake)

I'd like some input from a build-system maintainer on whether or not this is required.

```diff
diff --git a/cmake/Modules/OpmSatellites.cmake b/cmake/Modules/OpmSatellites.cmake
index d42f385..21288fa 100644
--- a/cmake/Modules/OpmSatellites.cmake
+++ b/cmake/Modules/OpmSatellites.cmake
@@ -210,12 +210,13 @@ macro(opm_add_test TestName)
   # explicitly specified.
   if (NOT CURTEST_SOURCES)
     set(CURTEST_SOURCES "")
+    set(_SDir "${CMAKE_CURRENT_SOURCE_DIR}")
     foreach(CURTEST_CANDIDATE "${CURTEST_EXE_NAME}.cpp"
                               "${CURTEST_EXE_NAME}.cc"
                               "tests/${CURTEST_EXE_NAME}.cpp"
                               "tests/${CURTEST_EXE_NAME}.cc")
-      if (EXISTS "${CURTEST_CANDIDATE}")
-        set(CURTEST_SOURCES "${CURTEST_CANDIDATE}")
+      if (EXISTS "${_SDir}/${CURTEST_CANDIDATE}")
+        set(CURTEST_SOURCES "${_SDir}/${CURTEST_CANDIDATE}")
       endif()
     endforeach()
   endif()
```

**Comment by andlaus** [comment]
ok, I suppose we should go with @bska's patch then. @bska could you please open a PR for `opm-common`?

**Comment by andlaus** [comment]
the thing which I puzzles me most about this issue: why is there an error in `OpmSatellites.cmake` if it is not used at all?

**Comment by bska** [comment]
> why is there an error in `OpmSatellites.cmake` if it is not used at all?

Could you elaborate a bit on why you say that?  As far as I can tell `opm_add_test` is a macro that's defined in `OpmSatellites.cmake`.  This macro uses
```cmake
add_executable("${CURTEST_EXE_NAME}" ${CURTEST_EXCLUDE_FROM_ALL} ${CURTEST_SOURCES})
```
to define a single test binary.  If `${CURTEST_SOURCES}` is empty, which it will be if none of the `EXISTS` tests fire, then the above becomes
```cmake
add_executable("${CURTEST_EXE_NAME}")
```
in the typical case of `${CURTEST_EXCLUDE_FROM_ALL}` being empty.  That, in turn, is an invalid call to `add_executable()` and CMake responds with "`incorrect number of parameters`".

**Comment by andlaus** [comment]
ah, ok: I forgot that Arne did copy that macro into `OpmSatellites.cmake` instead of keeping it separate. given your explanation, your patch seems fine. would you please open a PR for opm-common?

another thing I don't really get is that the existing `opm-material` tests seem to have worked fine. but maybe that's because they did not use the macro so far. (but then, why do the tests in `opm-parser` not have that problem? Probably it's not worth the time to hunt this down.)

**Comment by bska** [comment]
> would you please open a PR for opm-common?

See OPM/opm-common#49

> another thing I don't really get is that the existing opm-material tests seem to have worked fine. but maybe that's because they did not use the macro so far.

Yes, that's the reason.  The [`OpmFiles.cmake`](https://github.com/OPM/opm-common/blob/master/cmake/Modules/OpmFiles.cmake#L57-L59) module explicitly transforms a list of relative test file-names to canonical, full paths when adding tests to be built by [`opm_compile_satellites()`](https://github.com/OPM/opm-common/blob/master/cmake/Modules/OpmLibMain.cmake#L260-L264).

> why do the tests in opm-parser not have that problem?

Those tests pass an explicit list of `SOURCES` (see, e.g., [`runEclipseStateTests`](https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/tests/CMakeLists.txt)) and therefore bypass the automatic source file detection in `OpmSatellites.cmake`.

**Comment by andlaus** [comment]
once more, this seems like a gazillion special cases. Anyway I just merged your fix into `opm-common`.

@joakim-hove: does it work now?

**Comment by joakim-hove** [comment]
With the last minute fix: https://github.com/OPM/opm-common/pull/50 applied it works - yes!
