### ISSUE TITLE
Test failure:

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-material#72]
```txt
5/12 Test  #2: test_eclmateriallawmanager .......***Exception: Other  0.32 sec
terminate called after throwing an instance of 'std::logic_error'
  what():  [/private/jenkins/jenkins/RH6/workspace/opm-material-install-RH6/tests/test_eclmateriallawmanager.cpp:257] Discrepancy between the deck and the EclMaterialLawManager
```

**Comment by andlaus** [comment]
please merge #72 if it helps.

**Comment by joakim-hove** [comment]
I do not understand if this is a consequence of #73 or some changes to opm-common. But when building from scratch, with cmake version: 3.0.2 I now get:

```
CMake Error at /private/joaho/work/OPM/opm-common/cmake/Modules/OpmSatellites.cmake:286 (add_executable):
  add_executable cannot create target "test_fluidmatrixinteractions" because
  another target with the same name already exists.  The existing target is
  an executable created in source directory
  "/private/joaho/work/OPM/opm-material".  See documentation for policy
  CMP0002 for more details.
Call Stack (most recent call first):
  CMakeLists.txt:100 (opm_add_test)
```

I tried adding a `cmake_policy(SET CMP0002 NEW)` before the calls to `opm_add_test()` but that did not seem to help.

**Comment by andlaus** [comment]
> I do not understand if this is a consequence of #73 or some changes to opm-common. 

#73 is an unlikely candidate because it does not touch the build system in any way. As I interpret this, the `add_executable()` is called multiple times for `test_fluidmatrixinteractions`. Thats a bug even if CMP0002 would fix this. (which you said it does not.) I can only guess, but it may be an issue with a stale cache, possibly by another OPM module: did you remove and recreate all build directories or just the one for `opm-material`? also, what is the result of running `find -iname "*cmake*" | xargs grep fluidmatrixinteractions` in the `opm-material` source directory?

**Comment by joakim-hove** [comment]
> did you remove and recreate all build directories or just the one for opm-material?

I have now done a completely fresh build of `opm-common,opm-parser` and `opm-material` - problem persists.

>what is the result of running find -iname "*cmake*" | xargs grep fluidmatrixinteractions in the opm-material source directory?

```
cd opm-material
opm-material> find -iname "*cmake*" | xargs grep fluidmatrixinteractions
./CMakeLists.txt: opm_add_test(test_fluidmatrixinteractions)
./CMakeLists_files.cmake:	tests/test_fluidmatrixinteractions.cpp
```

**Comment by andlaus** [comment]
> `cd opm-material`
> `find -iname "*cmake*" | xargs grep fluidmatrixinteractions`
> `./CMakeLists.txt: opm_add_test(test_fluidmatrixinteractions)`
> `./CMakeLists_files.cmake:   tests/test_fluidmatrixinteractions.cpp`

That's the culprit: the test is added via `opm_add_test()` in `CMakeLists.txt` as well as by `./CMakeLists_files.cmake`. I'm just wondering why because in the it has been removed from `./CMakeLists_files.cmake` last week:

https://github.com/OPM/opm-material/blob/master/CMakeLists_files.cmake

**Comment by joakim-hove** [comment]
> I'm just wondering why because it has been removed from ./CMakeLists_files.cmake last week:

You are absolutely right - I 'resolved' a merge conflict incorrectly, essentially bringing the tests back to `CMakeLists_files.cmake` - my mistake. Sorry about the noise.

**Comment by joakim-hove** [comment]
I'll close this now.
