### ISSUE TITLE
Assertion in EclEpsScalingPoints.hpp when using flow_solvent

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-material#74]
Using the  solvent_test_suite with
```sh
./flow_solvent SPE1CASE2_SOLVENT.DATA
```
I get the following assertion: 
```
flow_solvent: opm-material/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp:247: void Opm::EclEpsScalingPointsInfo<Scalar>::extractUnscaled(Opm::DeckConstPtr, Opm::EclipseStateConstPtr, unsigned int) [with Scalar = double; Opm::DeckConstPtr = std::shared_ptr<const Opm::Deck>; Opm::EclipseStateConstPtr = std::shared_ptr<const Opm::EclipseState>]: Assertion `std::abs(maxKrw - maxKrg) < 1e-30' failed.
```
Raising the tolerance to 1e-12 leads to the same assertion.

**Comment by andlaus** [comment]
this assertation seems to be misplaced: I thought that the documentation says that the maximum relperms for both keywords must be identical, but upon reading more closely, I conclude that it is just the saturations. this should be fixed by #75. please re-open this issue if it did not...
